/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   transitions.c                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: smoreno <marvin@42.fr>                     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/05/02 16:30:29 by smoreno           #+#    #+#             */
/*   Updated: 2018/05/02 16:30:30 by smoreno          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "asm.h"

t_state							g_transitions[256][STATE_END] = {
	['.'][STALINE] = DOT_BEFORE_HEADER_FOUND,

	['c'][DOT_BEFORE_HEADER_FOUND] = DOT_C_FOUND,
	['n'][DOT_BEFORE_HEADER_FOUND] = DOT_N_FOUND,
	['a'][DOT_N_FOUND] = DOT_NA_FOUND,
	['m'][DOT_NA_FOUND] = DOT_NAM_FOUND,
	['e'][DOT_NAM_FOUND] = DOT_NAME_FOUND,
	[CHAR_BLANK][DOT_NAME_FOUND] = DOT_NAME_FOUND,
	['"'][DOT_NAME_FOUND] = NAME_FOUND,
	['"'][NAME_FOUND] = NAME_COMPLETED,
	[CHAR_BLANK][NAME_COMPLETED] = NAME_COMPLETED,
	[LINE_FEED][NAME_COMPLETED] = STALINE,

	['.'][NAME_COMPLETED] = DOT_BEFORE_COMMENT_FOUND,
	['o'][DOT_C_FOUND] = DOT_CO_FOUND,
	['m'][DOT_CO_FOUND] = DOT_COM_FOUND,
	['m'][DOT_COM_FOUND] = DOT_COMM_FOUND,
	['e'][DOT_COMM_FOUND] = DOT_COMME_FOUND,
	['n'][DOT_COMME_FOUND] = DOT_COMMEN_FOUND,
	['t'][DOT_COMMEN_FOUND] = DOT_COMMENT_FOUND,
	[CHAR_BLANK][DOT_COMMENT_FOUND] = DOT_COMMENT_FOUND,
	['"'][DOT_COMMENT_FOUND] = COMMENT_FOUND,
	['"'][COMMENT_FOUND] = COMMENT_COMPLETED,
	[CHAR_BLANK][COMMENT_COMPLETED] = COMMENT_COMPLETED,
	[LINE_FEED][COMMENT_COMPLETED] = STALINE,

	[CHAR_BLANK][STALINE] = STALINE,
	[LINE_FEED][STALINE] = STALINE,
	[LINE_FEED][STACOM] = STALINE,
	[COMMENT_CHAR][STALINE] = STACOM,
	[LABEL_CHAR][LABEL_DEF] = STALINE,

	['a'][STALINE] = A_FOUND,
	['f'][STALINE] = F_FOUND,
	['l'][STALINE] = L_FOUND,
	['o'][STALINE] = O_FOUND,
	['s'][STALINE] = S_FOUND,
	['x'][STALINE] = X_FOUND,
	['z'][STALINE] = Z_FOUND,

	['d'][A_FOUND] = AD_FOUND,
	['f'][A_FOUND] = AF_FOUND,
	['n'][A_FOUND] = AN_FOUND,

	['d'][AD_FOUND] = ADD_FOUND,
	[CHAR_BLANK][ADD_FOUND] = OPL2_OP1,
	['d'][AN_FOUND] = AND_FOUND,
	[CHAR_BLANK][AND_FOUND] = OPL1_OP1,

	['f'][AF_FOUND] = AFF_FOUND,
	[CHAR_BLANK][AFF_FOUND] = OPL8_OP1,

	['o'][F_FOUND] = FO_FOUND,
	['r'][FO_FOUND] = FOR_FOUND,
	['k'][FOR_FOUND] = FORK_FOUND,
	[CHAR_BLANK][FORK_FOUND] = OPL4_OP1,

	['d'][L_FOUND] = LD_FOUND,
	[CHAR_BLANK][LD_FOUND] = OPL5_OP1,
	['i'][LD_FOUND] = LDI_FOUND,
	[CHAR_BLANK][LDI_FOUND] = OPL3_OP1,

	['i'][L_FOUND] = LI_FOUND,
	['v'][LI_FOUND] = LIV_FOUND,
	['e'][LIV_FOUND] = LIVE_FOUND,
	[CHAR_BLANK][LIVE_FOUND] = OPL4_OP1,

	['f'][L_FOUND] = LF_FOUND,
	['o'][LF_FOUND] = LFO_FOUND,
	['r'][LFO_FOUND] = LFOR_FOUND,
	['k'][LFOR_FOUND] = LFORK_FOUND,
	[CHAR_BLANK][LFORK_FOUND] = OPL4_OP1,

	['l'][L_FOUND] = LL_FOUND,
	['d'][LL_FOUND] = LLD_FOUND,
	[CHAR_BLANK][LLD_FOUND] = OPL5_OP1,
	['i'][LLD_FOUND] = LLDI_FOUND,
	[CHAR_BLANK][LLDI_FOUND] = OPL3_OP1,

	['r'][O_FOUND] = OR_FOUND,
	[CHAR_BLANK][OR_FOUND] = OPL1_OP1,

	['t'][S_FOUND] = ST_FOUND,
	[CHAR_BLANK][ST_FOUND] = OPL6_OP1,
	['i'][ST_FOUND] = STI_FOUND,
	[CHAR_BLANK][STI_FOUND] = OPL7_OP1,

	['u'][S_FOUND] = SU_FOUND,
	['b'][SU_FOUND] = SUB_FOUND,
	[CHAR_BLANK][SUB_FOUND] = OPL2_OP1,

	['o'][X_FOUND] = XO_FOUND,
	['r'][XO_FOUND] = XOR_FOUND,
	[CHAR_BLANK][XOR_FOUND] = OPL1_OP1,

	['j'][Z_FOUND] = ZJ_FOUND,
	['m'][ZJ_FOUND] = ZJM_FOUND,
	['p'][ZJM_FOUND] = ZJMP_FOUND,
	[CHAR_BLANK][ZJMP_FOUND] = OPL4_OP1,

	[CHAR_BLANK][OPL1_OP1] = OPL1_OP1,

	[REGISTER_CHAR][OPL1_OP1] = OPL1_OP1REG,
	[DIRECT_CHAR][OPL1_OP1] = OPL1_OP1DIR,
	[LABEL_CHAR][OPL1_OP1DIR] = OPL1_OP1LABEL,
	[LABEL_CHAR][OPL1_OP1] = OPL1_OP1LABEL,
	[CHAR_BLANK][OPL1_OP1LABEL] = OPL1_OP1EB,
	[SEPARATOR_CHAR][OPL1_OP1LABEL] = OPL1_OP2,
	[CHAR_DIGIT][OPL1_OP1] = OPL1_OP1D,
	[CHAR_DIGIT][OPL1_OP1REG] = OPL1_OP1D,
	[CHAR_DIGIT][OPL1_OP1DIR] = OPL1_OP1D,
	[NEG_CHAR][OPL1_OP1] = OPL1_OP1NEG,
	[NEG_CHAR][OPL1_OP1DIR] = OPL1_OP1NEG,
	[CHAR_DIGIT][OPL1_OP1NEG] = OPL1_OP1D,

	[CHAR_DIGIT][OPL1_OP1D] = OPL1_OP1D,
	[CHAR_BLANK][OPL1_OP1D] = OPL1_OP1EB,
	[CHAR_BLANK][OPL1_OP1EB] = OPL1_OP1EB,
	[SEPARATOR_CHAR][OPL1_OP1D] = OPL1_OP2,
	[SEPARATOR_CHAR][OPL1_OP1EB] = OPL1_OP2,

	[CHAR_BLANK][OPL1_OP2] = OPL1_OP2,
	[REGISTER_CHAR][OPL1_OP2] = OPL1_OP2REG,
	[DIRECT_CHAR][OPL1_OP2] = OPL1_OP2DIR,
	[LABEL_CHAR][OPL1_OP2DIR] = OPL1_OP2LABEL,
	[LABEL_CHAR][OPL1_OP2] = OPL1_OP2LABEL,
	[CHAR_BLANK][OPL1_OP2LABEL] = OPL1_OP2EB,
	[SEPARATOR_CHAR][OPL1_OP2LABEL] = OPL1_OP3,
	[CHAR_DIGIT][OPL1_OP2] = OPL1_OP2D,
	[CHAR_DIGIT][OPL1_OP2REG] = OPL1_OP2D,
	[CHAR_DIGIT][OPL1_OP2DIR] = OPL1_OP2D,
	[NEG_CHAR][OPL1_OP2] = OPL1_OP2NEG,
	[NEG_CHAR][OPL1_OP2DIR] = OPL1_OP2NEG,
	[CHAR_DIGIT][OPL1_OP2NEG] = OPL1_OP2D,

	[CHAR_DIGIT][OPL1_OP2D] = OPL1_OP2D,
	[CHAR_BLANK][OPL1_OP2D] = OPL1_OP2EB,
	[CHAR_BLANK][OPL1_OP2EB] = OPL1_OP2EB,
	[SEPARATOR_CHAR][OPL1_OP2D] = OPL1_OP3,
	[SEPARATOR_CHAR][OPL1_OP2EB] = OPL1_OP3,

	[CHAR_BLANK][OPL1_OP3] = OPL1_OP3,
	[REGISTER_CHAR][OPL1_OP3] = OPL1_OP3REG,
	[CHAR_BLANK][OPL1_OP3LABEL] = OPL1_OP3EB,
	[LINE_FEED][OPL1_OP3LABEL] = STALINE,
	[CHAR_DIGIT][OPL1_OP3REG] = OPL1_OP3D,

	[CHAR_DIGIT][OPL1_OP3D] = OPL1_OP3D,
	[CHAR_BLANK][OPL1_OP3D] = OPL1_OP3EB,
	[CHAR_BLANK][OPL1_OP3EB] = OPL1_OP3EB,

	[LINE_FEED][OPL1_OP3EB] = STALINE,
	[LINE_FEED][OPL1_OP3D] = STALINE,
	[COMMENT_CHAR][OPL1_OP3EB] = STACOM,
	[COMMENT_CHAR][OPL1_OP3D] = STACOM,

	[CHAR_BLANK][OPL2_OP1] = OPL2_OP1,

	[REGISTER_CHAR][OPL2_OP1] = OPL2_OP1REG,
	[CHAR_BLANK][OPL2_OP1LABEL] = OPL2_OP1EB,
	[SEPARATOR_CHAR][OPL2_OP1LABEL] = OPL2_OP2,
	[CHAR_DIGIT][OPL2_OP1REG] = OPL2_OP1D,

	[CHAR_DIGIT][OPL2_OP1D] = OPL2_OP1D,
	[CHAR_BLANK][OPL2_OP1D] = OPL2_OP1EB,
	[CHAR_BLANK][OPL2_OP1EB] = OPL2_OP1EB,
	[SEPARATOR_CHAR][OPL2_OP1D] = OPL2_OP2,
	[SEPARATOR_CHAR][OPL2_OP1EB] = OPL2_OP2,

	[CHAR_BLANK][OPL2_OP2] = OPL2_OP2,
	[REGISTER_CHAR][OPL2_OP2] = OPL2_OP2REG,
	[CHAR_BLANK][OPL2_OP2LABEL] = OPL2_OP2EB,
	[SEPARATOR_CHAR][OPL2_OP2LABEL] = OPL2_OP3,
	[CHAR_DIGIT][OPL2_OP2REG] = OPL2_OP2D,

	[CHAR_DIGIT][OPL2_OP2D] = OPL2_OP2D,
	[CHAR_BLANK][OPL2_OP2D] = OPL2_OP2EB,
	[CHAR_BLANK][OPL2_OP2EB] = OPL2_OP2EB,
	[SEPARATOR_CHAR][OPL2_OP2D] = OPL2_OP3,
	[SEPARATOR_CHAR][OPL2_OP2EB] = OPL2_OP3,

	[CHAR_BLANK][OPL2_OP3] = OPL2_OP3,
	[REGISTER_CHAR][OPL2_OP3] = OPL2_OP3REG,
	[CHAR_BLANK][OPL2_OP3LABEL] = OPL2_OP3EB,
	[LINE_FEED][OPL2_OP3LABEL] = STALINE,
	[CHAR_DIGIT][OPL2_OP3REG] = OPL2_OP3D,

	[CHAR_DIGIT][OPL2_OP3D] = OPL2_OP3D,
	[CHAR_BLANK][OPL2_OP3D] = OPL2_OP3EB,
	[CHAR_BLANK][OPL2_OP3EB] = OPL2_OP3EB,

	[LINE_FEED][OPL2_OP3EB] = STALINE,
	[LINE_FEED][OPL2_OP3D] = STALINE,
	[COMMENT_CHAR][OPL2_OP3EB] = STACOM,
	[COMMENT_CHAR][OPL2_OP3D] = STACOM,

	[CHAR_BLANK][OPL3_OP1] = OPL3_OP1,

	[REGISTER_CHAR][OPL3_OP1] = OPL3_OP1REG,
	[DIRECT_CHAR][OPL3_OP1] = OPL3_OP1DIR,
	[LABEL_CHAR][OPL3_OP1DIR] = OPL3_OP1LABEL,
	[LABEL_CHAR][OPL3_OP1] = OPL3_OP1LABEL,
	[CHAR_BLANK][OPL3_OP1LABEL] = OPL3_OP1EB,
	[SEPARATOR_CHAR][OPL3_OP1LABEL] = OPL3_OP2,
	[CHAR_DIGIT][OPL3_OP1] = OPL3_OP1D,
	[CHAR_DIGIT][OPL3_OP1REG] = OPL3_OP1D,
	[CHAR_DIGIT][OPL3_OP1DIR] = OPL3_OP1D,
	[NEG_CHAR][OPL3_OP1] = OPL3_OP1NEG,
	[NEG_CHAR][OPL3_OP1DIR] = OPL3_OP1NEG,
	[CHAR_DIGIT][OPL3_OP1NEG] = OPL3_OP1D,

	[CHAR_DIGIT][OPL3_OP1D] = OPL3_OP1D,
	[CHAR_BLANK][OPL3_OP1D] = OPL3_OP1EB,
	[CHAR_BLANK][OPL3_OP1EB] = OPL3_OP1EB,
	[SEPARATOR_CHAR][OPL3_OP1D] = OPL3_OP2,
	[SEPARATOR_CHAR][OPL3_OP1EB] = OPL3_OP2,

	[CHAR_BLANK][OPL3_OP2] = OPL3_OP2,
	[REGISTER_CHAR][OPL3_OP2] = OPL3_OP2REG,
	[DIRECT_CHAR][OPL3_OP2] = OPL3_OP2DIR,
	[LABEL_CHAR][OPL3_OP2DIR] = OPL3_OP2LABEL,
	[LABEL_CHAR][OPL3_OP2] = OPL3_OP2LABEL,
	[CHAR_BLANK][OPL3_OP2LABEL] = OPL3_OP2EB,
	[SEPARATOR_CHAR][OPL3_OP2LABEL] = OPL3_OP3,
	[CHAR_DIGIT][OPL3_OP2REG] = OPL3_OP2D,
	[CHAR_DIGIT][OPL3_OP2DIR] = OPL3_OP2D,
	[NEG_CHAR][OPL3_OP2DIR] = OPL3_OP2NEG,
	[CHAR_DIGIT][OPL3_OP2NEG] = OPL3_OP2D,

	[CHAR_DIGIT][OPL3_OP2D] = OPL3_OP2D,
	[CHAR_BLANK][OPL3_OP2D] = OPL3_OP2EB,
	[CHAR_BLANK][OPL3_OP2EB] = OPL3_OP2EB,
	[SEPARATOR_CHAR][OPL3_OP2D] = OPL3_OP3,
	[SEPARATOR_CHAR][OPL3_OP2EB] = OPL3_OP3,

	[CHAR_BLANK][OPL3_OP3] = OPL3_OP3,
	[REGISTER_CHAR][OPL3_OP3] = OPL3_OP3REG,
	[CHAR_BLANK][OPL3_OP3LABEL] = OPL3_OP3EB,
	[LINE_FEED][OPL3_OP3LABEL] = STALINE,
	[CHAR_DIGIT][OPL3_OP3REG] = OPL3_OP3D,
	[CHAR_DIGIT][OPL3_OP3DIR] = OPL3_OP3D,

	[CHAR_DIGIT][OPL3_OP3D] = OPL3_OP3D,
	[CHAR_BLANK][OPL3_OP3D] = OPL3_OP3EB,
	[CHAR_BLANK][OPL3_OP3EB] = OPL3_OP3EB,

	[LINE_FEED][OPL3_OP3D] = STALINE,
	[LINE_FEED][OPL3_OP3EB] = STALINE,
	[COMMENT_CHAR][OPL3_OP3EB] = STACOM,
	[COMMENT_CHAR][OPL3_OP3D] = STACOM,

	[CHAR_BLANK][OPL4_OP1] = OPL4_OP1,

	[DIRECT_CHAR][OPL4_OP1] = OPL4_OP1DIR,
	[LABEL_CHAR][OPL4_OP1DIR] = OPL4_OP1LABEL,
	[LABEL_CHAR][OPL4_OP1] = OPL4_OP1LABEL,
	[CHAR_BLANK][OPL4_OP1LABEL] = OPL4_OP1EB,
	[LINE_FEED][OPL4_OP1LABEL] = STALINE,
	[CHAR_DIGIT][OPL4_OP1REG] = OPL4_OP1D,
	[CHAR_DIGIT][OPL4_OP1DIR] = OPL4_OP1D,
	[NEG_CHAR][OPL4_OP1DIR] = OPL4_OP1NEG,
	[CHAR_DIGIT][OPL4_OP1NEG] = OPL4_OP1D,

	[CHAR_DIGIT][OPL4_OP1D] = OPL4_OP1D,
	[CHAR_BLANK][OPL4_OP1D] = OPL4_OP1EB,
	[CHAR_BLANK][OPL4_OP1EB] = OPL4_OP1EB,

	[LINE_FEED][OPL4_OP1D] = STALINE,
	[LINE_FEED][OPL4_OP1EB] = STALINE,
	[COMMENT_CHAR][OPL4_OP1EB] = STACOM,
	[COMMENT_CHAR][OPL4_OP1D] = STACOM,

	[CHAR_BLANK][OPL5_OP1] = OPL5_OP1,

	[DIRECT_CHAR][OPL5_OP1] = OPL5_OP1DIR,
	[CHAR_DIGIT][OPL5_OP1] = OPL5_OP1D,
	[CHAR_DIGIT][OPL5_OP1REG] = OPL5_OP1D,
	[CHAR_DIGIT][OPL5_OP1DIR] = OPL5_OP1D,
	[LABEL_CHAR][OPL5_OP1DIR] = OPL5_OP1LABEL,
	[LABEL_CHAR][OPL5_OP1] = OPL5_OP1LABEL,
	[CHAR_BLANK][OPL5_OP1LABEL] = OPL5_OP1EB,
	[SEPARATOR_CHAR][OPL5_OP1LABEL] = OPL5_OP2,
	[NEG_CHAR][OPL5_OP1] = OPL5_OP1NEG,
	[NEG_CHAR][OPL5_OP1DIR] = OPL5_OP1NEG,
	[CHAR_DIGIT][OPL5_OP1NEG] = OPL5_OP1D,

	[CHAR_DIGIT][OPL5_OP1D] = OPL5_OP1D,
	[CHAR_BLANK][OPL5_OP1D] = OPL5_OP1EB,
	[CHAR_BLANK][OPL5_OP1EB] = OPL5_OP1EB,
	[SEPARATOR_CHAR][OPL5_OP1D] = OPL5_OP2,
	[SEPARATOR_CHAR][OPL5_OP1EB] = OPL5_OP2,

	[CHAR_BLANK][OPL5_OP2] = OPL5_OP2,
	[REGISTER_CHAR][OPL5_OP2] = OPL5_OP2REG,
	[CHAR_BLANK][OPL5_OP2LABEL] = OPL5_OP2EB,
	[SEPARATOR_CHAR][OPL5_OP2LABEL] = OPL5_OP3,
	[CHAR_DIGIT][OPL5_OP2REG] = OPL5_OP2D,
	[CHAR_DIGIT][OPL5_OP2DIR] = OPL5_OP2D,

	[CHAR_DIGIT][OPL5_OP2D] = OPL5_OP2D,
	[CHAR_BLANK][OPL5_OP2D] = OPL5_OP2EB,
	[CHAR_BLANK][OPL5_OP2EB] = OPL5_OP2EB,

	[LINE_FEED][OPL5_OP2EB] = STALINE,
	[LINE_FEED][OPL5_OP2D] = STALINE,
	[COMMENT_CHAR][OPL5_OP2EB] = STACOM,
	[COMMENT_CHAR][OPL5_OP2D] = STACOM,

	[CHAR_BLANK][OPL6_OP1] = OPL6_OP1,

	[REGISTER_CHAR][OPL6_OP1] = OPL6_OP1REG,
	[CHAR_BLANK][OPL6_OP1LABEL] = OPL6_OP1EB,
	[SEPARATOR_CHAR][OPL6_OP1LABEL] = OPL6_OP2,
	[CHAR_DIGIT][OPL6_OP1REG] = OPL6_OP1D,
	[CHAR_DIGIT][OPL6_OP1DIR] = OPL6_OP1D,

	[CHAR_DIGIT][OPL6_OP1D] = OPL6_OP1D,
	[CHAR_BLANK][OPL6_OP1D] = OPL6_OP1EB,
	[CHAR_BLANK][OPL6_OP1EB] = OPL6_OP1EB,
	[SEPARATOR_CHAR][OPL6_OP1D] = OPL6_OP2,
	[SEPARATOR_CHAR][OPL6_OP1EB] = OPL6_OP2,

	[CHAR_BLANK][OPL6_OP2] = OPL6_OP2,
	[REGISTER_CHAR][OPL6_OP2] = OPL6_OP2REG,
	[LABEL_CHAR][OPL6_OP2DIR] = OPL6_OP2LABEL,
	[LABEL_CHAR][OPL6_OP2] = OPL6_OP2LABEL,
	[CHAR_BLANK][OPL6_OP2LABEL] = OPL6_OP2EB,
	[LINE_FEED][OPL6_OP2LABEL] = STALINE,
	[CHAR_DIGIT][OPL6_OP2] = OPL6_OP2D,
	[CHAR_DIGIT][OPL6_OP2REG] = OPL6_OP2D,
	[CHAR_DIGIT][OPL6_OP2DIR] = OPL6_OP2D,
	[NEG_CHAR][OPL6_OP2] = OPL6_OP2NEG,
	[CHAR_DIGIT][OPL6_OP2NEG] = OPL6_OP2D,

	[CHAR_DIGIT][OPL6_OP2D] = OPL6_OP2D,
	[CHAR_BLANK][OPL6_OP2D] = OPL6_OP2EB,
	[CHAR_BLANK][OPL6_OP2EB] = OPL6_OP2EB,

	[LINE_FEED][OPL6_OP2EB] = STALINE,
	[LINE_FEED][OPL6_OP2D] = STALINE,
	[COMMENT_CHAR][OPL6_OP2EB] = STACOM,
	[COMMENT_CHAR][OPL6_OP2D] = STACOM,

	[CHAR_BLANK][OPL7_OP1] = OPL7_OP1,

	[REGISTER_CHAR][OPL7_OP1] = OPL7_OP1REG,
	[CHAR_DIGIT][OPL7_OP1REG] = OPL7_OP1D,
	[CHAR_DIGIT][OPL7_OP1DIR] = OPL7_OP1D,
	[CHAR_BLANK][OPL7_OP1LABEL] = OPL7_OP1EB,
	[SEPARATOR_CHAR][OPL7_OP1LABEL] = OPL7_OP2,

	[CHAR_DIGIT][OPL7_OP1D] = OPL7_OP1D,
	[CHAR_BLANK][OPL7_OP1D] = OPL7_OP1EB,
	[CHAR_BLANK][OPL7_OP1EB] = OPL7_OP1EB,
	[SEPARATOR_CHAR][OPL7_OP1D] = OPL7_OP2,
	[SEPARATOR_CHAR][OPL7_OP1EB] = OPL7_OP2,

	[CHAR_BLANK][OPL7_OP2] = OPL7_OP2,
	[REGISTER_CHAR][OPL7_OP2] = OPL7_OP2REG,
	[DIRECT_CHAR][OPL7_OP2] = OPL7_OP2DIR,
	[LABEL_CHAR][OPL7_OP2DIR] = OPL7_OP2LABEL,
	[LABEL_CHAR][OPL7_OP2] = OPL7_OP2LABEL,
	[CHAR_DIGIT][OPL7_OP2] = OPL7_OP2D,
	[NEG_CHAR][OPL7_OP2] = OPL7_OP2NEG,
	[CHAR_BLANK][OPL7_OP2LABEL] = OPL7_OP2EB,
	[SEPARATOR_CHAR][OPL7_OP2LABEL] = OPL7_OP3,
	[CHAR_DIGIT][OPL7_OP2REG] = OPL7_OP2D,
	[CHAR_DIGIT][OPL7_OP2DIR] = OPL7_OP2D,
	[NEG_CHAR][OPL7_OP2DIR] = OPL7_OP2NEG,
	[CHAR_DIGIT][OPL7_OP2NEG] = OPL7_OP2D,

	[CHAR_DIGIT][OPL7_OP2D] = OPL7_OP2D,
	[CHAR_BLANK][OPL7_OP2D] = OPL7_OP2EB,
	[CHAR_BLANK][OPL7_OP2EB] = OPL7_OP2EB,
	[SEPARATOR_CHAR][OPL7_OP2D] = OPL7_OP3,
	[SEPARATOR_CHAR][OPL7_OP2EB] = OPL7_OP3,

	[CHAR_BLANK][OPL7_OP3] = OPL7_OP3,
	[REGISTER_CHAR][OPL7_OP3] = OPL7_OP3REG,
	[DIRECT_CHAR][OPL7_OP3] = OPL7_OP3DIR,
	[LABEL_CHAR][OPL7_OP3DIR] = OPL7_OP3LABEL,
	[LABEL_CHAR][OPL7_OP3] = OPL7_OP3LABEL,
	[CHAR_BLANK][OPL7_OP3LABEL] = OPL7_OP3EB,
	[LINE_FEED][OPL7_OP3LABEL] = STALINE,
	[CHAR_DIGIT][OPL7_OP3] = OPL7_OP3D,
	[CHAR_DIGIT][OPL7_OP3REG] = OPL7_OP3D,
	[CHAR_DIGIT][OPL7_OP3DIR] = OPL7_OP3D,
	[NEG_CHAR][OPL7_OP3] = OPL7_OP3NEG,
	[NEG_CHAR][OPL7_OP3DIR] = OPL7_OP3NEG,
	[CHAR_DIGIT][OPL7_OP3NEG] = OPL7_OP3D,

	[CHAR_DIGIT][OPL7_OP3D] = OPL7_OP3D,
	[CHAR_BLANK][OPL7_OP3D] = OPL7_OP3EB,
	[CHAR_BLANK][OPL7_OP3EB] = OPL7_OP3EB,

	[LINE_FEED][OPL7_OP3EB] = STALINE,
	[LINE_FEED][OPL7_OP3D] = STALINE,
	[COMMENT_CHAR][OPL7_OP3EB] = STACOM,
	[COMMENT_CHAR][OPL7_OP3D] = STACOM,

	[CHAR_BLANK][OPL8_OP1] = OPL8_OP1,

	[REGISTER_CHAR][OPL8_OP1] = OPL8_OP1REG,
	[CHAR_DIGIT][OPL8_OP1REG] = OPL8_OP1D,
	[CHAR_BLANK][OPL8_OP1LABEL] = OPL8_OP1EB,
	[LINE_FEED][OPL8_OP1LABEL] = STALINE,

	[CHAR_DIGIT][OPL8_OP1D] = OPL8_OP1D,
	[CHAR_BLANK][OPL8_OP1D] = OPL8_OP1EB,
	[CHAR_BLANK][OPL8_OP1EB] = OPL8_OP1EB,

	[LINE_FEED][OPL8_OP1EB] = STALINE,
	[LINE_FEED][OPL8_OP1D] = STALINE,
	[COMMENT_CHAR][OPL8_OP1EB] = STACOM,
	[COMMENT_CHAR][OPL8_OP1D] = STACOM,
};

char								*g_state_strings[STATE_END] = {
	[INITIAL_STATE] = "INITIAL_STATE",

	[DOT_BEFORE_HEADER_FOUND] = "DOT_BEFORE_HEADER_FOUND",
	[DOT_N_FOUND] = "DOT_N_FOUND",
	[DOT_NA_FOUND] = "DOT_NA_FOUND",
	[DOT_NAM_FOUND] = "DOT_NAM_FOUND",
	[DOT_NAME_FOUND] = "DOT_NAME_FOUND",
	[NAME_FOUND] = "NAME_FOUND",
	[NAME_COMPLETED] = "NAME_COMPLETED",
	[DOT_BEFORE_COMMENT_FOUND] = "DOT_BEFORE_COMMENT_FOUND",
	[DOT_C_FOUND] = "DOT_C_FOUND",
	[DOT_CO_FOUND] = "DOT_CO_FOUND",
	[DOT_COM_FOUND] = "DOT_COM_FOUND",
	[DOT_COMM_FOUND] = "DOT_COMM_FOUND",
	[DOT_COMME_FOUND] = "DOT_COMME_FOUND",
	[DOT_COMMEN_FOUND] = "DOT_COMMEN_FOUND",
	[DOT_COMMENT_FOUND] = "DOT_COMMENT_FOUND",
	[COMMENT_FOUND] = "COMMENT_FOUND",
	[COMMENT_COMPLETED] = "COMMENT_COMPLETED",

	[STALINE] = "STALINE",
	[STACOM] = "STACOM",
	[LABEL_DEF] = "LABEL_DEF",

	[A_FOUND] = "A_FOUND",
	[F_FOUND] = "F_FOUND",
	[L_FOUND] = "L_FOUND",
	[O_FOUND] = "O_FOUND",
	[S_FOUND] = "S_FOUND",
	[X_FOUND] = "X_FOUND",
	[Z_FOUND] = "Z_FOUND",

	[AD_FOUND] = "AD_FOUND",
	[AF_FOUND] = "AF_FOUND",
	[AN_FOUND] = "AN_FOUND",

	[AFF_FOUND] = "AFF_FOUND",

	[ADD_FOUND] = "ADD_FOUND",
	[AND_FOUND] = "AND_FOUND",

	[FO_FOUND] = "FO_FOUND",
	[FOR_FOUND] = "FOR_FOUND",
	[FORK_FOUND] = "FORK_FOUND",

	[LD_FOUND] = "LD_FOUND",
	[LDI_FOUND] = "LDI_FOUND",

	[LI_FOUND] = "LI_FOUND",
	[LIV_FOUND] = "LIV_FOUND",
	[LIVE_FOUND] = "LIVE_FOUND",

	[LF_FOUND] = "LF_FOUND",
	[LFO_FOUND] = "LFO_FOUND",
	[LFOR_FOUND] = "LFOR_FOUND",
	[LFORK_FOUND] = "LFORK_FOUND",

	[LL_FOUND] = "LL_FOUND",
	[LLD_FOUND] = "LLD_FOUND",
	[LLDI_FOUND] = "LLDI_FOUND",

	[OR_FOUND] = "OR_FOUND",

	[ST_FOUND] = "ST_FOUND",
	[STI_FOUND] = "STI_FOUND",

	[SU_FOUND] = "SU_FOUND",
	[SUB_FOUND] = "SUB_FOUND",

	[XO_FOUND] = "XO_FOUND",
	[XOR_FOUND] = "XOR_FOUND",

	[ZJ_FOUND] = "ZJ_FOUND",
	[ZJM_FOUND] = "ZJM_FOUND",
	[ZJMP_FOUND] = "ZJMP_FOUND",

	[OPL1] = "OPL1",
	[OPL1_OP1] = "OPL1_OP1",
	[OPL1_OP2] = "OPL1_OP2",
	[OPL1_OP3] = "OPL1_OP3",
	[OPL1_OP1LABEL] = "OPL1_OP1LABEL",
	[OPL1_OP2LABEL] = "OPL1_OP2LABEL",
	[OPL1_OP3LABEL] = "OPL1_OP3LABEL",
	[OPL1_OP1REG] = "OPL1_OP1REG",
	[OPL1_OP2REG] = "OPL1_OP2REG",
	[OPL1_OP3REG] = "OPL1_OP3REG",
	[OPL1_OP1DIR] = "OPL1_OP1DIR",
	[OPL1_OP2DIR] = "OPL1_OP2DIR",
	[OPL1_OP3DIR] = "OPL1_OP3DIR",
	[OPL1_OP1D] = "OPL1_OP1D",
	[OPL1_OP2D] = "OPL1_OP2D",
	[OPL1_OP3D] = "OPL1_OP3D",
	[OPL1_OP1EB] = "OPL1_OP1EB",
	[OPL1_OP2EB] = "OPL1_OP2EB",
	[OPL1_OP3EB] = "OPL1_OP3EB",

	[OPL2] = "OPL2",
	[OPL2_OP1] = "OPL2_OP1",
	[OPL2_OP2] = "OPL2_OP2",
	[OPL2_OP3] = "OPL2_OP3",
	[OPL2_OP1LABEL] = "OPL2_OP1LABEL",
	[OPL2_OP2LABEL] = "OPL2_OP2LABEL",
	[OPL2_OP3LABEL] = "OPL2_OP3LABEL",
	[OPL2_OP1REG] = "OPL2_OP1REG",
	[OPL2_OP2REG] = "OPL2_OP2REG",
	[OPL2_OP3REG] = "OPL2_OP3REG",
	[OPL2_OP1DIR] = "OPL2_OP1DIR",
	[OPL2_OP2DIR] = "OPL2_OP2DIR",
	[OPL2_OP3DIR] = "OPL2_OP3DIR",
	[OPL2_OP1D] = "OPL2_OP1D",
	[OPL2_OP2D] = "OPL2_OP2D",
	[OPL2_OP3D] = "OPL2_OP3D",
	[OPL2_OP1EB] = "OPL2_OP1EB",
	[OPL2_OP2EB] = "OPL2_OP2EB",
	[OPL2_OP3EB] = "OPL2_OP3EB",

	[OPL3] = "OPL3",
	[OPL3_OP1] = "OPL3_OP1",
	[OPL3_OP2] = "OPL3_OP2",
	[OPL3_OP3] = "OPL3_OP3",
	[OPL3_OP1LABEL] = "OPL3_OP1LABEL",
	[OPL3_OP2LABEL] = "OPL3_OP2LABEL",
	[OPL3_OP3LABEL] = "OPL3_OP3LABEL",
	[OPL3_OP1REG] = "OPL3_OP1REG",
	[OPL3_OP2REG] = "OPL3_OP2REG",
	[OPL3_OP3REG] = "OPL3_OP3REG",
	[OPL3_OP1DIR] = "OPL3_OP1DIR",
	[OPL3_OP2DIR] = "OPL3_OP2DIR",
	[OPL3_OP3DIR] = "OPL3_OP3DIR",
	[OPL3_OP1D] = "OPL3_OP1D",
	[OPL3_OP2D] = "OPL3_OP2D",
	[OPL3_OP3D] = "OPL3_OP3D",
	[OPL3_OP1EB] = "OPL3_OP1EB",
	[OPL3_OP2EB] = "OPL3_OP2EB",
	[OPL3_OP3EB] = "OPL3_OP3EB",

	[OPL4] = "OPL4",
	[OPL4_OP1] = "OPL4_OP1",
	[OPL4_OP2] = "OPL4_OP2",
	[OPL4_OP3] = "OPL4_OP3",
	[OPL4_OP1LABEL] = "OPL4_OP1LABEL",
	[OPL4_OP2LABEL] = "OPL4_OP2LABEL",
	[OPL4_OP3LABEL] = "OPL4_OP3LABEL",
	[OPL4_OP1REG] = "OPL4_OP1REG",
	[OPL4_OP2REG] = "OPL4_OP2REG",
	[OPL4_OP3REG] = "OPL4_OP3REG",
	[OPL4_OP1DIR] = "OPL4_OP1DIR",
	[OPL4_OP2DIR] = "OPL4_OP2DIR",
	[OPL4_OP3DIR] = "OPL4_OP3DIR",
	[OPL4_OP1D] = "OPL4_OP1D",
	[OPL4_OP2D] = "OPL4_OP2D",
	[OPL4_OP3D] = "OPL4_OP3D",
	[OPL4_OP1EB] = "OPL4_OP1EB",
	[OPL4_OP2EB] = "OPL4_OP2EB",
	[OPL4_OP3EB] = "OPL4_OP3EB",

	[OPL5] = "OPL5",
	[OPL5_OP1] = "OPL5_OP1",
	[OPL5_OP2] = "OPL5_OP2",
	[OPL5_OP3] = "OPL5_OP3",
	[OPL5_OP1LABEL] = "OPL5_OP1LABEL",
	[OPL5_OP2LABEL] = "OPL5_OP2LABEL",
	[OPL5_OP3LABEL] = "OPL5_OP3LABEL",
	[OPL5_OP1REG] = "OPL5_OP1REG",
	[OPL5_OP2REG] = "OPL5_OP2REG",
	[OPL5_OP3REG] = "OPL5_OP3REG",
	[OPL5_OP1DIR] = "OPL5_OP1DIR",
	[OPL5_OP2DIR] = "OPL5_OP2DIR",
	[OPL5_OP3DIR] = "OPL5_OP3DIR",
	[OPL5_OP1D] = "OPL5_OP1D",
	[OPL5_OP2D] = "OPL5_OP2D",
	[OPL5_OP3D] = "OPL5_OP3D",
	[OPL5_OP1EB] = "OPL5_OP1EB",
	[OPL5_OP2EB] = "OPL5_OP2EB",
	[OPL5_OP3EB] = "OPL5_OP3EB",

	[OPL6] = "OPL6",
	[OPL6_OP1] = "OPL6_OP1",
	[OPL6_OP2] = "OPL6_OP2",
	[OPL6_OP3] = "OPL6_OP3",
	[OPL6_OP1LABEL] = "OPL6_OP1LABEL",
	[OPL6_OP2LABEL] = "OPL6_OP2LABEL",
	[OPL6_OP3LABEL] = "OPL6_OP3LABEL",
	[OPL6_OP1REG] = "OPL6_OP1REG",
	[OPL6_OP2REG] = "OPL6_OP2REG",
	[OPL6_OP3REG] = "OPL6_OP3REG",
	[OPL6_OP1DIR] = "OPL6_OP1DIR",
	[OPL6_OP2DIR] = "OPL6_OP2DIR",
	[OPL6_OP3DIR] = "OPL6_OP3DIR",
	[OPL6_OP1D] = "OPL6_OP1D",
	[OPL6_OP2D] = "OPL6_OP2D",
	[OPL6_OP3D] = "OPL6_OP3D",
	[OPL6_OP1EB] = "OPL6_OP1EB",
	[OPL6_OP2EB] = "OPL6_OP2EB",
	[OPL6_OP3EB] = "OPL6_OP3EB",

	[OPL7] = "OPL7",
	[OPL7_OP1] = "OPL7_OP1",
	[OPL7_OP2] = "OPL7_OP2",
	[OPL7_OP3] = "OPL7_OP3",
	[OPL7_OP1LABEL] = "OPL7_OP1LABEL",
	[OPL7_OP2LABEL] = "OPL7_OP2LABEL",
	[OPL7_OP3LABEL] = "OPL7_OP3LABEL",
	[OPL7_OP1REG] = "OPL7_OP1REG",
	[OPL7_OP2REG] = "OPL7_OP2REG",
	[OPL7_OP3REG] = "OPL7_OP3REG",
	[OPL7_OP1DIR] = "OPL7_OP1DIR",
	[OPL7_OP2DIR] = "OPL7_OP2DIR",
	[OPL7_OP3DIR] = "OPL7_OP3DIR",
	[OPL7_OP1D] = "OPL7_OP1D",
	[OPL7_OP2D] = "OPL7_OP2D",
	[OPL7_OP3D] = "OPL7_OP3D",
	[OPL7_OP1EB] = "OPL7_OP1EB",
	[OPL7_OP2EB] = "OPL7_OP2EB",
	[OPL7_OP3EB] = "OPL7_OP3EB",

	[OPL8] = "OPL8",
	[OPL8_OP1] = "OPL8_OP1",
	[OPL8_OP2] = "OPL8_OP2",
	[OPL8_OP3] = "OPL8_OP3",
	[OPL8_OP1LABEL] = "OPL8_OP1LABEL",
	[OPL8_OP2LABEL] = "OPL8_OP2LABEL",
	[OPL8_OP3LABEL] = "OPL8_OP3LABEL",
	[OPL8_OP1REG] = "OPL8_OP1REG",
	[OPL8_OP2REG] = "OPL8_OP2REG",
	[OPL8_OP3REG] = "OPL8_OP3REG",
	[OPL8_OP1DIR] = "OPL8_OP1DIR",
	[OPL8_OP2DIR] = "OPL8_OP2DIR",
	[OPL8_OP3DIR] = "OPL8_OP3DIR",
	[OPL8_OP1D] = "OPL8_OP1D",
	[OPL8_OP2D] = "OPL8_OP2D",
	[OPL8_OP3D] = "OPL8_OP3D",
	[OPL8_OP1EB] = "OPL8_OP1EB",
	[OPL8_OP2EB] = "OPL8_OP2EB",
	[OPL8_OP3EB] = "OPL8_OP3EB",
};

static t_state						g_op_label_states[STATE_END] = {
	OPL1_OP1LABEL,
	OPL1_OP2LABEL,
	OPL1_OP3LABEL,
	OPL2_OP1LABEL,
	OPL2_OP2LABEL,
	OPL2_OP3LABEL,
	OPL3_OP1LABEL,
	OPL3_OP2LABEL,
	OPL3_OP3LABEL,
	OPL4_OP1LABEL,
	OPL4_OP2LABEL,
	OPL4_OP3LABEL,
	OPL5_OP1LABEL,
	OPL5_OP2LABEL,
	OPL5_OP3LABEL,
	OPL6_OP1LABEL,
	OPL6_OP2LABEL,
	OPL6_OP3LABEL,
	OPL7_OP1LABEL,
	OPL7_OP2LABEL,
	OPL7_OP3LABEL,
	OPL8_OP1LABEL,
	OPL8_OP2LABEL,
	OPL8_OP3LABEL,
};

static char							g_character_class[256] = {
	['0'] = CHAR_DIGIT,
	['1'] = CHAR_DIGIT,
	['2'] = CHAR_DIGIT,
	['3'] = CHAR_DIGIT,
	['4'] = CHAR_DIGIT,
	['5'] = CHAR_DIGIT,
	['6'] = CHAR_DIGIT,
	['7'] = CHAR_DIGIT,
	['8'] = CHAR_DIGIT,
	['9'] = CHAR_DIGIT,
	[' '] = CHAR_BLANK,
	['\t'] = CHAR_BLANK,
	['\v'] = CHAR_BLANK,
	['\f'] = CHAR_BLANK,
	['\r'] = CHAR_BLANK
};

static t_state						g_state_ignore[STATE_END] = {
	[STACOM] = STACOM,
	[NAME_FOUND] = NAME_FOUND,
	[COMMENT_FOUND] = COMMENT_FOUND,
};

static inline void					load_label_transitions_recursive(
	const t_state current_state)
{
	int								i;
	t_state							next_state;

	i = 0;
	while (LABEL_CHARS[i])
	{
		if ((next_state = g_transitions[(int)LABEL_CHARS[i]][current_state]))
			load_label_transitions_recursive(next_state);
		else
			g_transitions[(int)LABEL_CHARS[i]][current_state] = LABEL_DEF;
		++i;
	}
	if (STALINE != current_state)
		g_transitions[LABEL_CHAR][current_state] = STALINE;
}

void								load_label_transitions(void)
{
	int								i;
	int								e;

	load_label_transitions_recursive(STALINE);
	i = 0;
	while (LABEL_CHARS[i])
		g_transitions[(int)LABEL_CHARS[i++]][LABEL_DEF] = LABEL_DEF;
	e = 0;
	while (g_op_label_states[e])
	{
		i = 0;
		while (LABEL_CHARS[i])
			g_transitions[(int)LABEL_CHARS[i++]][g_op_label_states[e]] =
				g_op_label_states[e];
		++e;
	}
}

t_state								get_new_state(void)
{
	t_state							new_state;
	uint8_t							tested_input;

	tested_input = g_character_class[(int)*g_line_ptr] ?
		g_character_class[(int)*g_line_ptr] : *g_line_ptr;
	new_state = g_transitions[(int)tested_input][g_asm.state];
	if (!new_state)
		new_state = g_state_ignore[g_asm.state];
	if (!new_state && *g_line_ptr > 127)
		new_state = g_asm.state;
	if (!new_state)
		exit(error_message_with_char(ERROR_SYNTAX_AT, *g_line_ptr));
	return (new_state);
}
